### ISSUE TITLE
Changed nordvpn stability and usability score to  score to a 1

### ISSUE THREAD

**Issue by person1234-ux** [techlore/VPN-reviews#25]
Nordvpn recently became unusable on iso and ubuntu with sometimes it works on ios

**Comment by techlore-official** [comment]
Do you mind sharing more details, data, recreation steps, etc. 

Currently usability scoring is limited to personal reviews of each service. If I can recreate it this is something I may be able to update in our next update review for them.

**Comment by techlore-official** [comment]
Sending a final ping before I close this issue
