### ISSUE TITLE
Adding whether the VPN owns the server or rents them to the chart

### ISSUE THREAD

**Issue by justaguydoinghisstuff** [techlore/VPN-reviews#26]
Hi,
I don't know if this is the correct channel to suggest this. But I wanted to suggest to include in the VPN chart whether the VPN owns the server or is renting them. I know the logging policy should be enough but from what i understood the hosts can see everything on their machines.

**Comment by techlore-official** [comment]
Completely agree. 

Our review protocol is long overdue for updates and this is something that will very likely make its way in to make criteria stricter.

**Comment by techlore-official** [comment]
This has now been included in review protocol 3.1: https://github.com/techlore/VPN-reviews/commit/2ef684760350e0eff451bbb8c0c9f920529de3b0
