### ISSUE TITLE
Speedteam results need to have same fields

### ISSUE THREAD

**Issue by d3ward** [techlore/VPN-reviews#35]
As working on Speedteam visualizer in a dedicated page ,after fetching the data , the table can't relate the connection of 2 specific fields . 
There is like [IVPN.csv](https://github.com/techlore/VPN-reviews/blob/master/speedteam/Results/IVPN.csv) that have a Mega Download % speedtest but then other csv like [Astrill.csv](https://github.com/techlore/VPN-reviews/blob/master/speedteam/Results/Astrill.csv) that doesn't have the Mega Download % , and instead it have Ubuntu Download Test.

Suggestion to use the same field test for any test results

**Comment by techlore-official** [comment]
I believe I got this fixed, check out the PR here: https://github.com/techlore/VPN-reviews/commit/de14870d1da6fb7ecfe5e7b303c287ecfdea6e50

let me know if that fixed it!
