### ISSUE TITLE
Surfshark server infrastructure independent audit

### ISSUE THREAD

**Issue by lachlankm** [techlore/VPN-reviews#40]
I don't know if this is the right place but surfshark had a new Infrastructure audit happen on its by Cure53 but it seem like the VPN chart has not been updated with this info.
https://surfshark.com/blog/surfshark-server-infrastructure-undergoes-independent-audit
https://surfshark.com/wp-content/uploads/2021/05/SRF-02-summary.pdf
![image](https://user-images.githubusercontent.com/40618678/124232694-5930b700-db55-11eb-9e92-c3c620d3e36e.png)

**Comment by techlore-official** [comment]
Great catch! Just updated the chart to reflect this. You'll find the commit here: https://github.com/techlore/VPN-reviews/commit/d35c1a5bf557279c3aaf66fe1b9db21b29cc051a
