### ISSUE TITLE
Add testing methodology for Wireguard

### ISSUE THREAD

**Issue by uranuspucksaxophone** [techlore/VPN-reviews#42]
Profiles and instructions aren't available for Wireguard.

**Comment by techlore-official** [comment]
Many instructions aren't available and this is an ongoing issue I need to work on! Eventually I will want to have every category broken down clearly for people

**Comment by henryistaken** [comment]
Closing this issue as it now falls under the new one: https://github.com/techlore/VPN-reviews/issues/51
