### ISSUE TITLE
Is Surfshark helping privacy causes?

### ISSUE THREAD

**Issue by Donnnno** [techlore/VPN-reviews#46]
Hi! While Surfshark is still not open-source (and probably never will be), I found this on the [surfshark site](https://surfshark.com/about-us) about supporting the open internet:

![image](https://user-images.githubusercontent.com/31142286/139876546-53cb9472-ce48-4abd-a4ac-98701aa00346.png)

But the VPN chart says this:

![image](https://user-images.githubusercontent.com/31142286/139876249-af263960-8b15-460c-a2d2-c01962447814.png)

Are these organizations considered as privacy causes too?

**Comment by techlore-official** [comment]
https://github.com/techlore/VPN-reviews/commit/235160d7b9ceb85006bab98f3bf85581cd73834b
Just updated, good catch!

**Comment by Donnnno** [comment]
Cool, thanks!
