### ISSUE TITLE
Should ProtonVPN's usage score be higher? 

### ISSUE THREAD

**Issue by Donnnno** [techlore/VPN-reviews#48]
Hi again, another question: Should ProtonVPN's usage score be higher now that it's included WireGuard and their Linux client is out of beta? 

https://github.com/ProtonVPN/linux-app
https://protonvpn.com/download-linux

There's also an android TV app and Chromebook app. 

https://protonvpn.com/download-androidtv
https://protonvpn.com/download-chromebook

**Comment by uranuspucksaxophone** [comment]
The linux client is terrible, ProtonVPN says it's an "Advanced Linux client", when it does not even have one basic configuration toggle and lacking esential features like Wireguard and Autoconnect on boot.

**Comment by henryistaken** [comment]
Hey there, as of the latest commit we've actually migrated away from all review-based scoring on our ends. So anything pertaining to the review protocol has been omitted from the chart. The relevant data point of Proton offering a Linux GUI is labeled accordingly so I'm going to close this issue. Thanks for the feedback!
