### ISSUE TITLE
Suggestion: VPN Chart - Freeze First Column and Row

### ISSUE THREAD

**Issue by 8227846265** [techlore/VPN-reviews#49]
Hi, I would like to suggest adding an option to freeze the first column and row since as the list grows, it's really hard to navigate if you're at the rightmost columns already.

When in there, it's really hard to see if the row you're looking at is the same VPN you were looking at when you're on the leftmost section of the chart. 

This experience goes more awful if you're on mobile view.

**Comment by henryistaken** [comment]
This (to my knowledge) is dependent on the client you're using, in this case it sounds like GitHub. This isn't something you can implement into the CSV format. Generally speaking, the CSV format is bad for a lot of things and I'd like to move away from it for more reasons than this. To view the chart, I recommend using git and opening the CSV with your favorite text editor or document editor that handles CSV
