### ISSUE TITLE
Mullvad supports killswitch

### ISSUE THREAD

**Issue by grubeli** [techlore/VPN-reviews#52]
![image](https://user-images.githubusercontent.com/74614193/152810673-7c717465-ee60-4286-a500-1ab2243755c3.png)

**Comment by henryistaken** [comment]
Yep, as @rusticadam mentioned. "System killswitch" is on a system-wide level, and an "App Killswitch" is a killswitch on a per-program/app basis. It's just a different feature. There is a lot of confusion over this, so we'll be hoping to write out some better documentation to cover these things.
