### ISSUE TITLE
404 Error on repo landing page for first "Click Here" link to https://techlore.tech/vpnchart 

### ISSUE THREAD

**Issue by Carewen** [techlore/VPN-reviews#59]
Thanks for all the work you do. When coming here to review these efforts on GitHub I clicked on the "Click Here" link on the repo's landing page: https://github.com/techlore/VPN-reviews

> Specifically, To view our full VPN comparison chart [Click Here](https://techlore.tech/vpnchart) | [Contribute Here](https://github.com/techlore/VPN-reviews/blob/master/VPNchart.csv)

Notice that the first link gives a 404 error for the following: https://techlore.tech/vpnchart  (at the time of this issue submission).

This is easily fixed by updating the source documentation to offer a working link, or updating the existing web template/url path.

**Comment by henryistaken** [comment]
Thanks for catching this! Just fixed it, along with a lot of other outdated info in the readme. https://github.com/techlore/VPN-reviews/commit/6550a8396560bcb060212d1e412dff5661fc61cb

**Comment by Carewen** [comment]
You're welcome. It takes a crowd to maintain a community resource. :)
