### ISSUE TITLE
Remove two providers from the honest marketing section

### ISSUE THREAD

**Issue by ghost** [techlore/VPN-reviews#64]
I took a closer look at all the services that still have the check for honest marketing and found two additional services that don't deserve it, in my opinion.

**StrongVPN**: Let's start with this statement: "Right now, your private data is at risk without a VPN. It’s not too late to take action — use StrongVPN to shield your personal information from the spying eyes of your ISP..." My biggest issue with this is their use of urgency and fear to market their service.

Here is another statement: "Anonymous Browsing" "With the protection of StrongVPN, your browsing history and activity will be virtually invisible. Stay hidden from any prying eyes by using one of our anonymous IP addresses and surf the web without a trace." A little over the top, would you say? You can find both of these on [this page](https://strongvpn.com/isp-tracking/).

**HideMyAss**: This one is shorter, but using disinformation to sell your service is unacceptable. "Why get a VPN for privacy? Because without a VPN, you don’t have any. A VPN encrypts your connection to the internet, keeping your info safe from spies and hackers, while connecting you to a remote server to hide your IP address, so governments, your ISP, and more can’t see what you do online." The biggest problem is the claim that you supposedly cannot have privacy on the internet without a VPN. Even though this may seem like a relatively small thing, I think it is a big and false claim that should not be tolerated. https://www.hidemyass.com/privacy

**Comment by henryistaken** [comment]
Agreed, will remove these two VPNs as well in an upcoming update.
